package com.project.back_end.models;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import jakarta.validation.constraints.*;

/**
 * Prescription document stored in MongoDB (collection: prescriptions).
 */
@Document(collection = "prescriptions")
public class Prescription {

    // 1. MongoDB id (auto-generated by Mongo)
    @Id
    private String id;

    // 2. Patient's full name (required, 3–100 characters)
    @NotNull(message = "patientName cannot be null")
    @Size(min = 3, max = 100, message = "patientName must be between 3 and 100 characters")
    private String patientName;

    // 3. Reference to Appointment id (required)
    @NotNull(message = "appointmentId cannot be null")
    private Long appointmentId;

    // 4. Medication name (required, 3–100 characters)
    @NotNull(message = "medication cannot be null")
    @Size(min = 3, max = 100, message = "medication must be between 3 and 100 characters")
    private String medication;

    // 5. Dosage details (required, 3–20 characters)
    @NotNull(message = "dosage cannot be null")
    @Size(min = 3, max = 20, message = "dosage must be between 3 and 20 characters")
    private String dosage;

    // 6. Optional doctor notes (max 200 characters)
    @Size(max = 200, message = "doctorNotes must be at most 200 characters")
    private String doctorNotes;

    // No-arg constructor (required by frameworks)
    public Prescription() {}

    // Parameterized constructor to initialize main fields
    public Prescription(String patientName, Long appointmentId, String medication, String dosage, String doctorNotes) {
        this.patientName = patientName;
        this.appointmentId = appointmentId;
        this.medication = medication;
        this.dosage = dosage;
        this.doctorNotes = doctorNotes;
    }

    // ---------- Getters and Setters ----------

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getPatientName() {
        return patientName;
    }

    public void setPatientName(String patientName) {
        this.patientName = patientName;
    }

    public Long getAppointmentId() {
        return appointmentId;
    }

    public void setAppointmentId(Long appointmentId) {
        this.appointmentId = appointmentId;
    }

    public String getMedication() {
        return medication;
    }

    public void setMedication(String medication) {
        this.medication = medication;
    }

    public String getDosage() {
        return dosage;
    }

    public void setDosage(String dosage) {
        this.dosage = dosage;
    }

    public String getDoctorNotes() {
        return doctorNotes;
    }

    public void setDoctorNotes(String doctorNotes) {
        this.doctorNotes = doctorNotes;
    }
}
